base: &base
  s3_secret_access_key: "7JMgPQVLxInDvCHf0QZCRbgxBGNT7kjBl+mCunux"
  s3_access_key_id: "AKIAID3ZK2N2NUNIHBTQ"
  # region: "s3-us-west-1.amazonaws.com" 
development:
  <<: *base
  s3_bucket: "zenlabtest"
production:
  <<: *base
  s3_bucket: "zenlab"