development:
  cloud_name: zenlab
  api_key: '828811776446474'
  api_secret: fdUQgLMnxySyfY_uARulSm_b_fs
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: zenlab
  api_key: '828811776446474'
  api_secret: fdUQgLMnxySyfY_uARulSm_b_fs
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: zenlab
  api_key: '828811776446474'
  api_secret: fdUQgLMnxySyfY_uARulSm_b_fs
  enhance_image_tag: true
  static_image_support: false
